apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: lab
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual