apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: lab
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /data/mysql