apiVersion: v1
kind: Service
metadata:
  name: paymybuddy-backend
  namespace: lab
spec:
  selector:
    app: paymybuddy-backend
  ports:
    - protocol: TCP
      port: 8080        # Le port interne du service
      targetPort: 8080  # Le port auquel ton application écoute à l'intérieur du conteneur
      nodePort: 30008   # Le port exposé sur chaque nœud du cluster
  type: NodePort       # Utiliser NodePort pour exposer le service
