apiVersion: v1
kind: Service
metadata:
  name: paymybuddy-db
  namespace: lab
spec:
  selector:
    app: paymybuddy-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None  # Pas d'IP externe
