apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymybuddy-db
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymybuddy-db
  template:
    metadata:
      labels:
        app: paymybuddy-db
    spec:
      containers:
        - name: paymybuddy-db
          image: mysql:latest
          envFrom:
            - secretRef:
                name: paymybuddy-secret
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: initdb
          hostPath:
            path: /home/vagrant/lab-esgi/initdb
            type: Directory